# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - nanami

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://acr20220514alterbooth2.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e8933b2b65d5497a881c44f06fa9eee1 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_aa9da3c69e614e8da0f383f1f78baa5f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: acr20220514alterbooth2.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e8933b2b65d5497a881c44f06fa9eee1 }}/nanami-2:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'nanami'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d143c7ed14784289a1647ec1d86388e6 }}
        images: 'acr20220514alterbooth2.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e8933b2b65d5497a881c44f06fa9eee1 }}/nanami-2:${{ github.sha }}'